dist:
  name: otelcol-lgtm
  description: Local OpenTelemetry Collector binary with LGTM exporter
  output_path: ./dist
  otelcol_version: 0.147.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.147.0
  - gomod: github.com/mattgp/lgtmexporter v0.147.0
    path: /build/lgtmexporter

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.147.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.147.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.147.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.147.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.147.0
