// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                    metric.Meter
	mu                       sync.Mutex
	registrations            []metric.Registration
	ExporterLGTMSentSamples  metric.Int64Counter
	ExporterLGTMSentRequests metric.Int64Counter
	ExporterLGTMWriteLatency metric.Int64Histogram
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ExporterLGTMSentSamples, err = builder.meter.Int64Counter(
		"otelcol_exporter_lgtm_sent_samples",
		metric.WithDescription("Number of LGTM samples sent"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExporterLGTMSentRequests, err = builder.meter.Int64Counter(
		"otelcol_exporter_lgtm_sent_requests",
		metric.WithDescription("Number of LGTM requests sent"),
		metric.WithUnit("1"),
	)
	builder.ExporterLGTMWriteLatency, err = builder.meter.Int64Histogram(
		"otelcol_exporter_lgtm_write_latency",
		metric.WithDescription("Latency of LGTM write requests"),
		metric.WithUnit("ms"),
		metric.WithExplicitBucketBoundaries([]float64{5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000}...),
	)

	errs = errors.Join(errs, err)
	return &builder, errs
}
